version: "3.9"

services:
  backend:
    build:
      context: ./src/SmartDataAnalyst.Backend
      dockerfile: backend.dockerfile
    container_name: smartdataanalyst-backend
    ports:
      - "8000:8000"
    env_file:
      - src/SmartDataAnalyst.Backend/.env
    volumes:
      - ./src/SmartDataAnalyst.Backend:/app
    restart: unless-stopped
    networks:
      - sda-network
  
  frontend:
    build:
      context: ./src/SmartDataAnalyst.Frontend
      dockerfile: frontend.dockerfile
    container_name: smartdataanalyst-frontend

    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:8000
    restart: unless-stopped
    networks:
      - sda-network

networks:
  sda-network:
    driver: bridge
    