name: F:\Projects\SmartDataAnalyst\env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.12.12=h716150d_1
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.10.5
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - distro==1.9.0
      - fastapi==0.121.0
      - fonttools==4.60.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jiter==0.11.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - numpy==2.3.4
      - openai==2.7.1
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.49.3
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uvicorn==0.38.0
prefix: F:\Projects\SmartDataAnalyst\env
